### ISSUE TITLE
No document 

### ISSUE THREAD

**Issue by MarcSteven** [PyCon/startup-row#1]
I think you should forget to upload the doc to describe the best practices in the software engineer.

**Comment by ejodlowska** [comment]
We are not certain what is meant by your comment and how it pertains to PyCon's Startup Row. Please elaborate.

**Comment by MarcSteven** [comment]
@ejodlowska I mean it doesn't include pdf file. But two days earlier you uploaded it. Thank for your sharing!!
Now it's time to close this issue!!
Cool
